/*
 * Ext JS Library 2.0.2
 * Copyright(c) 2006-2008, Ext JS, LLC.
 * licensing@extjs.com
 * 
 * http://extjs.com/license
 */

Ext.onReady(function(){
	
	var quansf = new Ext.Panel({
		layout:"table",
		layoutConfig:{
		  columns:5
		},
		defaults:{
			
		},
		items:[{
			width:150,
			html:"<font size=1></font>"
		  },{
		  	width:80,
		    html:"<font size=1>第一次</font>"
		    //width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第二次</font>"
		   // width:.1
		  },{
		  	width:80,
		    html:"<font size=1>第三次</font>"
		   // width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第四次</font>"
		    //width:.2
		  },{
		    html:"<font size=1>称量瓶(盘)号</font>"
		  },{
		   		xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		    		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>称量瓶(盘)质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>称重瓶(盘)质量+试样质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>试样质量m(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>烘干后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>检查性试验后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>干燥后煤样减少的质量m1(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>全水分Mt=m1/m*100(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>平均值Mt(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>审核</font>"
		  },{
			xtype:"textfield",
			width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		   xtype:"textfield",
		   width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  }]
		});
		
	var shuif = new Ext.Panel({
		layout:"table",
		layoutConfig:{
		  columns:5
		},
		defaults:{
			
		},
		items:[{
			width:150,
			html:"<font size=1></font>"
		  },{
		  	width:80,
		    html:"<font size=1>第一次</font>"
		    //width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第二次</font>"
		   // width:.1
		  },{
		  	width:80,
		    html:"<font size=1>第三次</font>"
		   // width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第四次</font>"
		    //width:.2
		  },{
		    html:"<font size=1>称量瓶(盘)号</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>称量瓶(盘)质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>称重瓶(盘)质量+试样质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>试样质量m(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>烘干后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>检查性试验后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>干燥后煤样减少的质量m1(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>水分Mad=m1/m*100(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>平均值Mad(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>审核</font>"
		  },{
			xtype:"textfield",
			width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		   xtype:"textfield",
		   width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  }]
		});

	var huif = new Ext.Panel({
		layout:"table",
		layoutConfig:{
		  columns:5
		},
		defaults:{
			
		},
		items:[{
			width:150,
			html:"<font size=1></font>"
		  },{
		  	width:80,
		    html:"<font size=1>第一次</font>"
		    //width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第二次</font>"
		   // width:.1
		  },{
		  	width:80,
		    html:"<font size=1>第三次</font>"
		   // width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第四次</font>"
		    //width:.2
		  },{
		    html:"<font size=1>灰皿号</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>灰皿质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>灰皿质量+试样质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>试样质量m(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>加热后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>检查性试验后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>残留物的质量m1(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>灰分Aad</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>平均值Aad(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>审核</font>"
		  },{
			xtype:"textfield",
			width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		   xtype:"textfield",
		   width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  }]
		});

	var huiff = new Ext.Panel({
		layout:"table",
		layoutConfig:{
		  columns:5
		},
		defaults:{
			
		},
		items:[{
			width:150,
			html:"<font size=1></font>"
		  },{
		  	width:80,
		    html:"<font size=1>第一次</font>"
		    //width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第二次</font>"
		   // width:.1
		  },{
		  	width:80,
		    html:"<font size=1>第三次</font>"
		   // width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第四次</font>"
		    //width:.2
		  },{
		    html:"<font size=1>坩埚号</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>坩埚质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>坩埚质量+试样质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>试样质量m(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>加热后总质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>煤样加热后减少的质量m1(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>挥发分Vad=m1/m*100-Mad(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>挥发分Vdaf(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>平均值Vdaf(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>审核</font>"
		  },{
			xtype:"textfield",
			width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		   xtype:"textfield",
		   width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  }]
		});
	
	var liuf = new Ext.Panel({
		layout:"table",
		layoutConfig:{
		  columns:5
		},
		defaults:{
			
		},
		items:[{
			width:150,
			html:"<font size=1></font>"
		  },{
		  	width:80,
		    html:"<font size=1>第一次</font>"
		    //width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第二次</font>"
		   // width:.1
		  },{
		  	width:80,
		    html:"<font size=1>第三次</font>"
		   // width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第四次</font>"
		    //width:.2
		  },{
		    html:"<font size=1>器皿号</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>器皿质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>器皿质量+试样质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>试样质量m(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>全硫St,ad(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>全硫St,d(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>平均值St,d(%)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>审核</font>"
		  },{
			xtype:"textfield",
			width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		   xtype:"textfield",
		   width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  }]
		});
		
		
	var farl = new Ext.Panel({
		layout:"table",
		layoutConfig:{
		  columns:5
		},
		defaults:{
			
		},
		items:[{
			width:150,
			html:"<font size=1></font>"
		  },{
		  	width:80,
		    html:"<font size=1>第一次</font>"
		    //width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第二次</font>"
		   // width:.1
		  },{
		  	width:80,
		    html:"<font size=1>第三次</font>"
		   // width:.2
		  },{
		  	width:80,
		    html:"<font size=1>第四次</font>"
		    //width:.2
		  },{
		    html:"<font size=1>坩埚号</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		      }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>坩埚质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>坩埚质量+试样质量(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>试样质量m(g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>Qb,ad(J/g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size=1>Qgr,ad(J/g)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>Qnet,ar(MJ/kg)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>平均值Qnet,ar(MJ/kg)</font>"
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    items:[{
		        xtype:"numberfield",
		        width:80,
		        //fieldLabel:"标签",
		        name:"numtxt_value"
		     }]
		  },{
		    html:"<font size = 1>审核</font>"
		  },{
			xtype:"textfield",
			width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		    xtype:"textfield",
		    width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  },{
		   xtype:"textfield",
		   width:80,
			//fieldLabel:"标签",
			name:"txt_value"
		  }]
		});

		

    var viewport = new Ext.Viewport({
        layout:'border',
        items:[
          {
            xtype:'portal',
            region:'center',
            margins:'35 5 5 0',
            items:[{
                columnWidth:.49,
                style:'padding:10px 0 10px 10px',
                items:[{
                    title: '全水分Mt',
                    //layout:'fit'
                    //height:,
                    //tools: tools,
                    items: quansf
                },{
                    title: '挥发分Vad',
                    //tools: tools,
                    items: huiff
                },{
                    title: '全硫',
                    //tools: tools,
                    items: liuf
                }]
            },{
                columnWidth:.49,
                style:'padding:10px 0 10px 10px',
                items:[{
                    title: '水分Mad',
                    //tools: tools,
                    items: shuif
                },{
                    title: '灰分Aad',
                    //tools: tools,
                    items: huif
                },{
                    title: '发热量',
                    //tools: tools,
                    items: farl
                }]
            }]
        }]     
    });
    var panel1 = new Ext.Panel({
    //el:'formDiv',
    items:[viewport]
    });
    panel1.render('formDiv');
    
});